query HomePageFiles {
  any_files: files_files(limit: 15, order_by: { _block_range: desc }) {
    id
    name
    chunk {
      data
      uploadOptions: upload_options
    }
    file_cids {
      chunk {
        data
        uploadOptions: upload_options
      }
    }
  }
  picture_files: files_files(
    limit: 15
    order_by: { _block_range: desc }
    where: { _or: [{ name: { _ilike: "%jpg" } }, { name: { _ilike: "%png" } }] }
  ) {
    id
    name
    chunk {
      data
      uploadOptions: upload_options
    }
    file_cids {
      chunk {
        data
        uploadOptions: upload_options
      }
    }
  }
}
